// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/cell.proto

package cell

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevastateCellContentsRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Data          *DevastateCellContentsRequest_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevastateCellContentsRequest) Reset() {
	*x = DevastateCellContentsRequest{}
	mi := &file_api_cell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevastateCellContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevastateCellContentsRequest) ProtoMessage() {}

func (x *DevastateCellContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevastateCellContentsRequest.ProtoReflect.Descriptor instead.
func (*DevastateCellContentsRequest) Descriptor() ([]byte, []int) {
	return file_api_cell_proto_rawDescGZIP(), []int{0}
}

func (x *DevastateCellContentsRequest) GetData() *DevastateCellContentsRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DevastateCellContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevastateCellContentsResponse) Reset() {
	*x = DevastateCellContentsResponse{}
	mi := &file_api_cell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevastateCellContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevastateCellContentsResponse) ProtoMessage() {}

func (x *DevastateCellContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevastateCellContentsResponse.ProtoReflect.Descriptor instead.
func (*DevastateCellContentsResponse) Descriptor() ([]byte, []int) {
	return file_api_cell_proto_rawDescGZIP(), []int{1}
}

type FullDevastateCellContentsRequest struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Data          *FullDevastateCellContentsRequest_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullDevastateCellContentsRequest) Reset() {
	*x = FullDevastateCellContentsRequest{}
	mi := &file_api_cell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullDevastateCellContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullDevastateCellContentsRequest) ProtoMessage() {}

func (x *FullDevastateCellContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullDevastateCellContentsRequest.ProtoReflect.Descriptor instead.
func (*FullDevastateCellContentsRequest) Descriptor() ([]byte, []int) {
	return file_api_cell_proto_rawDescGZIP(), []int{2}
}

func (x *FullDevastateCellContentsRequest) GetData() *FullDevastateCellContentsRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type FullDevastateCellContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullDevastateCellContentsResponse) Reset() {
	*x = FullDevastateCellContentsResponse{}
	mi := &file_api_cell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullDevastateCellContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullDevastateCellContentsResponse) ProtoMessage() {}

func (x *FullDevastateCellContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullDevastateCellContentsResponse.ProtoReflect.Descriptor instead.
func (*FullDevastateCellContentsResponse) Descriptor() ([]byte, []int) {
	return file_api_cell_proto_rawDescGZIP(), []int{3}
}

type DevastateCellContentsRequest_Data struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Name          string                                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CellContents  *DevastateCellContentsRequest_Data_CellContents `protobuf:"bytes,2,opt,name=cell_contents,json=cellContents,proto3" json:"cell_contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevastateCellContentsRequest_Data) Reset() {
	*x = DevastateCellContentsRequest_Data{}
	mi := &file_api_cell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevastateCellContentsRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevastateCellContentsRequest_Data) ProtoMessage() {}

func (x *DevastateCellContentsRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_cell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevastateCellContentsRequest_Data.ProtoReflect.Descriptor instead.
func (*DevastateCellContentsRequest_Data) Descriptor() ([]byte, []int) {
	return file_api_cell_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DevastateCellContentsRequest_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DevastateCellContentsRequest_Data) GetCellContents() *DevastateCellContentsRequest_Data_CellContents {
	if x != nil {
		return x.CellContents
	}
	return nil
}

type DevastateCellContentsRequest_Data_CellContents struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExternalOrderId *string                `protobuf:"bytes,1,opt,name=external_order_id,json=externalOrderId,proto3,oneof" json:"external_order_id,omitempty"`
	Sku             string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity        uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DevastateCellContentsRequest_Data_CellContents) Reset() {
	*x = DevastateCellContentsRequest_Data_CellContents{}
	mi := &file_api_cell_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevastateCellContentsRequest_Data_CellContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevastateCellContentsRequest_Data_CellContents) ProtoMessage() {}

func (x *DevastateCellContentsRequest_Data_CellContents) ProtoReflect() protoreflect.Message {
	mi := &file_api_cell_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevastateCellContentsRequest_Data_CellContents.ProtoReflect.Descriptor instead.
func (*DevastateCellContentsRequest_Data_CellContents) Descriptor() ([]byte, []int) {
	return file_api_cell_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *DevastateCellContentsRequest_Data_CellContents) GetExternalOrderId() string {
	if x != nil && x.ExternalOrderId != nil {
		return *x.ExternalOrderId
	}
	return ""
}

func (x *DevastateCellContentsRequest_Data_CellContents) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *DevastateCellContentsRequest_Data_CellContents) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type FullDevastateCellContentsRequest_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullDevastateCellContentsRequest_Data) Reset() {
	*x = FullDevastateCellContentsRequest_Data{}
	mi := &file_api_cell_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullDevastateCellContentsRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullDevastateCellContentsRequest_Data) ProtoMessage() {}

func (x *FullDevastateCellContentsRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_cell_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullDevastateCellContentsRequest_Data.ProtoReflect.Descriptor instead.
func (*FullDevastateCellContentsRequest_Data) Descriptor() ([]byte, []int) {
	return file_api_cell_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FullDevastateCellContentsRequest_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_cell_proto protoreflect.FileDescriptor

const file_api_cell_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/cell.proto\x12\x13dopov.p.julian.cell\"\xf7\x02\n" +
	"\x1cDevastateCellContentsRequest\x12J\n" +
	"\x04data\x18\x01 \x01(\v26.dopov.p.julian.cell.DevastateCellContentsRequest.DataR\x04data\x1a\x8a\x02\n" +
	"\x04Data\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12h\n" +
	"\rcell_contents\x18\x02 \x01(\v2C.dopov.p.julian.cell.DevastateCellContentsRequest.Data.CellContentsR\fcellContents\x1a\x83\x01\n" +
	"\fCellContents\x12/\n" +
	"\x11external_order_id\x18\x01 \x01(\tH\x00R\x0fexternalOrderId\x88\x01\x01\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantityB\x14\n" +
	"\x12_external_order_id\"\x1f\n" +
	"\x1dDevastateCellContentsResponse\"\x8e\x01\n" +
	" FullDevastateCellContentsRequest\x12N\n" +
	"\x04data\x18\x01 \x01(\v2:.dopov.p.julian.cell.FullDevastateCellContentsRequest.DataR\x04data\x1a\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"#\n" +
	"!FullDevastateCellContentsResponse2\x98\x02\n" +
	"\x04Cell\x12\x80\x01\n" +
	"\x15DevastateCellContents\x121.dopov.p.julian.cell.DevastateCellContentsRequest\x1a2.dopov.p.julian.cell.DevastateCellContentsResponse\"\x00\x12\x8c\x01\n" +
	"\x19FullDevastateCellContents\x125.dopov.p.julian.cell.FullDevastateCellContentsRequest\x1a6.dopov.p.julian.cell.FullDevastateCellContentsResponse\"\x00B1Z/github.com/dopov-p/julian/internal/pb/cell;cellb\x06proto3"

var (
	file_api_cell_proto_rawDescOnce sync.Once
	file_api_cell_proto_rawDescData []byte
)

func file_api_cell_proto_rawDescGZIP() []byte {
	file_api_cell_proto_rawDescOnce.Do(func() {
		file_api_cell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cell_proto_rawDesc), len(file_api_cell_proto_rawDesc)))
	})
	return file_api_cell_proto_rawDescData
}

var file_api_cell_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_cell_proto_goTypes = []any{
	(*DevastateCellContentsRequest)(nil),                   // 0: dopov.p.julian.cell.DevastateCellContentsRequest
	(*DevastateCellContentsResponse)(nil),                  // 1: dopov.p.julian.cell.DevastateCellContentsResponse
	(*FullDevastateCellContentsRequest)(nil),               // 2: dopov.p.julian.cell.FullDevastateCellContentsRequest
	(*FullDevastateCellContentsResponse)(nil),              // 3: dopov.p.julian.cell.FullDevastateCellContentsResponse
	(*DevastateCellContentsRequest_Data)(nil),              // 4: dopov.p.julian.cell.DevastateCellContentsRequest.Data
	(*DevastateCellContentsRequest_Data_CellContents)(nil), // 5: dopov.p.julian.cell.DevastateCellContentsRequest.Data.CellContents
	(*FullDevastateCellContentsRequest_Data)(nil),          // 6: dopov.p.julian.cell.FullDevastateCellContentsRequest.Data
}
var file_api_cell_proto_depIdxs = []int32{
	4, // 0: dopov.p.julian.cell.DevastateCellContentsRequest.data:type_name -> dopov.p.julian.cell.DevastateCellContentsRequest.Data
	6, // 1: dopov.p.julian.cell.FullDevastateCellContentsRequest.data:type_name -> dopov.p.julian.cell.FullDevastateCellContentsRequest.Data
	5, // 2: dopov.p.julian.cell.DevastateCellContentsRequest.Data.cell_contents:type_name -> dopov.p.julian.cell.DevastateCellContentsRequest.Data.CellContents
	0, // 3: dopov.p.julian.cell.Cell.DevastateCellContents:input_type -> dopov.p.julian.cell.DevastateCellContentsRequest
	2, // 4: dopov.p.julian.cell.Cell.FullDevastateCellContents:input_type -> dopov.p.julian.cell.FullDevastateCellContentsRequest
	1, // 5: dopov.p.julian.cell.Cell.DevastateCellContents:output_type -> dopov.p.julian.cell.DevastateCellContentsResponse
	3, // 6: dopov.p.julian.cell.Cell.FullDevastateCellContents:output_type -> dopov.p.julian.cell.FullDevastateCellContentsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_cell_proto_init() }
func file_api_cell_proto_init() {
	if File_api_cell_proto != nil {
		return
	}
	file_api_cell_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cell_proto_rawDesc), len(file_api_cell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cell_proto_goTypes,
		DependencyIndexes: file_api_cell_proto_depIdxs,
		MessageInfos:      file_api_cell_proto_msgTypes,
	}.Build()
	File_api_cell_proto = out.File
	file_api_cell_proto_goTypes = nil
	file_api_cell_proto_depIdxs = nil
}
