// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/cell.proto

package cell

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cell_DevastateCellContents_FullMethodName     = "/dopov.p.julian.cell.Cell/DevastateCellContents"
	Cell_FullDevastateCellContents_FullMethodName = "/dopov.p.julian.cell.Cell/FullDevastateCellContents"
)

// CellClient is the client API for Cell service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CellClient interface {
	// Частичное опустошение товаров из ячейки
	DevastateCellContents(ctx context.Context, in *DevastateCellContentsRequest, opts ...grpc.CallOption) (*DevastateCellContentsResponse, error)
	// Полное опустошение товаров из ячейки
	FullDevastateCellContents(ctx context.Context, in *FullDevastateCellContentsRequest, opts ...grpc.CallOption) (*FullDevastateCellContentsResponse, error)
}

type cellClient struct {
	cc grpc.ClientConnInterface
}

func NewCellClient(cc grpc.ClientConnInterface) CellClient {
	return &cellClient{cc}
}

func (c *cellClient) DevastateCellContents(ctx context.Context, in *DevastateCellContentsRequest, opts ...grpc.CallOption) (*DevastateCellContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DevastateCellContentsResponse)
	err := c.cc.Invoke(ctx, Cell_DevastateCellContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellClient) FullDevastateCellContents(ctx context.Context, in *FullDevastateCellContentsRequest, opts ...grpc.CallOption) (*FullDevastateCellContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullDevastateCellContentsResponse)
	err := c.cc.Invoke(ctx, Cell_FullDevastateCellContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CellServer is the server API for Cell service.
// All implementations must embed UnimplementedCellServer
// for forward compatibility.
type CellServer interface {
	// Частичное опустошение товаров из ячейки
	DevastateCellContents(context.Context, *DevastateCellContentsRequest) (*DevastateCellContentsResponse, error)
	// Полное опустошение товаров из ячейки
	FullDevastateCellContents(context.Context, *FullDevastateCellContentsRequest) (*FullDevastateCellContentsResponse, error)
	mustEmbedUnimplementedCellServer()
}

// UnimplementedCellServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCellServer struct{}

func (UnimplementedCellServer) DevastateCellContents(context.Context, *DevastateCellContentsRequest) (*DevastateCellContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DevastateCellContents not implemented")
}
func (UnimplementedCellServer) FullDevastateCellContents(context.Context, *FullDevastateCellContentsRequest) (*FullDevastateCellContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FullDevastateCellContents not implemented")
}
func (UnimplementedCellServer) mustEmbedUnimplementedCellServer() {}
func (UnimplementedCellServer) testEmbeddedByValue()              {}

// UnsafeCellServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CellServer will
// result in compilation errors.
type UnsafeCellServer interface {
	mustEmbedUnimplementedCellServer()
}

func RegisterCellServer(s grpc.ServiceRegistrar, srv CellServer) {
	// If the following call panics, it indicates UnimplementedCellServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cell_ServiceDesc, srv)
}

func _Cell_DevastateCellContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevastateCellContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServer).DevastateCellContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cell_DevastateCellContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServer).DevastateCellContents(ctx, req.(*DevastateCellContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cell_FullDevastateCellContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullDevastateCellContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServer).FullDevastateCellContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cell_FullDevastateCellContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServer).FullDevastateCellContents(ctx, req.(*FullDevastateCellContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cell_ServiceDesc is the grpc.ServiceDesc for Cell service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cell_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dopov.p.julian.cell.Cell",
	HandlerType: (*CellServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DevastateCellContents",
			Handler:    _Cell_DevastateCellContents_Handler,
		},
		{
			MethodName: "FullDevastateCellContents",
			Handler:    _Cell_FullDevastateCellContents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/cell.proto",
}
