// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Вид ячейки
type CellKind int32

const (
	CellKind_CELL_KIND_UNSPECIFIED                CellKind = 0
	CellKind_CELL_KIND_WAREHOUSE_STORAGE          CellKind = 1
	CellKind_CELL_KIND_WAREHOUSE_HANDLE_CONTAINER CellKind = 2
	CellKind_CELL_KIND_WAREHOUSE_BOX              CellKind = 3
)

// Enum value maps for CellKind.
var (
	CellKind_name = map[int32]string{
		0: "CELL_KIND_UNSPECIFIED",
		1: "CELL_KIND_WAREHOUSE_STORAGE",
		2: "CELL_KIND_WAREHOUSE_HANDLE_CONTAINER",
		3: "CELL_KIND_WAREHOUSE_BOX",
	}
	CellKind_value = map[string]int32{
		"CELL_KIND_UNSPECIFIED":                0,
		"CELL_KIND_WAREHOUSE_STORAGE":          1,
		"CELL_KIND_WAREHOUSE_HANDLE_CONTAINER": 2,
		"CELL_KIND_WAREHOUSE_BOX":              3,
	}
)

func (x CellKind) Enum() *CellKind {
	p := new(CellKind)
	*p = x
	return p
}

func (x CellKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_admin_proto_enumTypes[0].Descriptor()
}

func (CellKind) Type() protoreflect.EnumType {
	return &file_api_admin_proto_enumTypes[0]
}

func (x CellKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellKind.Descriptor instead.
func (CellKind) EnumDescriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{0}
}

// Тип хранимых в ячейки товаров
type CellContentType int32

const (
	CellContentType_CELL_CONTENT_TYPE_UNSPECIFIED        CellContentType = 0
	CellContentType_CELL_CONTENT_TYPE_EXPENDABLE_PRODUCT CellContentType = 1
	CellContentType_CELL_CONTENT_TYPE_MAIN_PRODUCT       CellContentType = 2
	CellContentType_CELL_CONTENT_TYPE_OVERSIZED_PRODUCT  CellContentType = 3
	CellContentType_CELL_CONTENT_TYPE_EXPENDABLE_LIQUID  CellContentType = 4
	CellContentType_CELL_CONTENT_TYPE_MAIN_LIQUID        CellContentType = 5
)

// Enum value maps for CellContentType.
var (
	CellContentType_name = map[int32]string{
		0: "CELL_CONTENT_TYPE_UNSPECIFIED",
		1: "CELL_CONTENT_TYPE_EXPENDABLE_PRODUCT",
		2: "CELL_CONTENT_TYPE_MAIN_PRODUCT",
		3: "CELL_CONTENT_TYPE_OVERSIZED_PRODUCT",
		4: "CELL_CONTENT_TYPE_EXPENDABLE_LIQUID",
		5: "CELL_CONTENT_TYPE_MAIN_LIQUID",
	}
	CellContentType_value = map[string]int32{
		"CELL_CONTENT_TYPE_UNSPECIFIED":        0,
		"CELL_CONTENT_TYPE_EXPENDABLE_PRODUCT": 1,
		"CELL_CONTENT_TYPE_MAIN_PRODUCT":       2,
		"CELL_CONTENT_TYPE_OVERSIZED_PRODUCT":  3,
		"CELL_CONTENT_TYPE_EXPENDABLE_LIQUID":  4,
		"CELL_CONTENT_TYPE_MAIN_LIQUID":        5,
	}
)

func (x CellContentType) Enum() *CellContentType {
	p := new(CellContentType)
	*p = x
	return p
}

func (x CellContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_admin_proto_enumTypes[1].Descriptor()
}

func (CellContentType) Type() protoreflect.EnumType {
	return &file_api_admin_proto_enumTypes[1]
}

func (x CellContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellContentType.Descriptor instead.
func (CellContentType) EnumDescriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{1}
}

type Cell struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind            CellKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=dopov.p.julian.admin.CellKind" json:"kind,omitempty"`
	ContentType     CellContentType        `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=dopov.p.julian.admin.CellContentType" json:"content_type,omitempty"`
	CanHasFewOrders bool                   `protobuf:"varint,4,opt,name=can_has_few_orders,json=canHasFewOrders,proto3" json:"can_has_few_orders,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_api_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Cell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cell) GetKind() CellKind {
	if x != nil {
		return x.Kind
	}
	return CellKind_CELL_KIND_UNSPECIFIED
}

func (x *Cell) GetContentType() CellContentType {
	if x != nil {
		return x.ContentType
	}
	return CellContentType_CELL_CONTENT_TYPE_UNSPECIFIED
}

func (x *Cell) GetCanHasFewOrders() bool {
	if x != nil {
		return x.CanHasFewOrders
	}
	return false
}

type CreateCellRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *CreateCellRequest_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCellRequest) Reset() {
	*x = CreateCellRequest{}
	mi := &file_api_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellRequest) ProtoMessage() {}

func (x *CreateCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellRequest.ProtoReflect.Descriptor instead.
func (*CreateCellRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCellRequest) GetData() *CreateCellRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateCellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCellResponse) Reset() {
	*x = CreateCellResponse{}
	mi := &file_api_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellResponse) ProtoMessage() {}

func (x *CreateCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellResponse.ProtoReflect.Descriptor instead.
func (*CreateCellResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{2}
}

type MarkCellDeletedRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Data          *MarkCellDeletedRequest_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCellDeletedRequest) Reset() {
	*x = MarkCellDeletedRequest{}
	mi := &file_api_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCellDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCellDeletedRequest) ProtoMessage() {}

func (x *MarkCellDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCellDeletedRequest.ProtoReflect.Descriptor instead.
func (*MarkCellDeletedRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{3}
}

func (x *MarkCellDeletedRequest) GetData() *MarkCellDeletedRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type MarkCellDeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCellDeletedResponse) Reset() {
	*x = MarkCellDeletedResponse{}
	mi := &file_api_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCellDeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCellDeletedResponse) ProtoMessage() {}

func (x *MarkCellDeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCellDeletedResponse.ProtoReflect.Descriptor instead.
func (*MarkCellDeletedResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{4}
}

type CreateCellRequest_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          *Cell                  `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCellRequest_Data) Reset() {
	*x = CreateCellRequest_Data{}
	mi := &file_api_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCellRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellRequest_Data) ProtoMessage() {}

func (x *CreateCellRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellRequest_Data.ProtoReflect.Descriptor instead.
func (*CreateCellRequest_Data) Descriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateCellRequest_Data) GetCell() *Cell {
	if x != nil {
		return x.Cell
	}
	return nil
}

type MarkCellDeletedRequest_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCellDeletedRequest_Data) Reset() {
	*x = MarkCellDeletedRequest_Data{}
	mi := &file_api_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCellDeletedRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCellDeletedRequest_Data) ProtoMessage() {}

func (x *MarkCellDeletedRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCellDeletedRequest_Data.ProtoReflect.Descriptor instead.
func (*MarkCellDeletedRequest_Data) Descriptor() ([]byte, []int) {
	return file_api_admin_proto_rawDescGZIP(), []int{3, 0}
}

func (x *MarkCellDeletedRequest_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_admin_proto protoreflect.FileDescriptor

const file_api_admin_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/admin.proto\x12\x14dopov.p.julian.admin\"\xc5\x01\n" +
	"\x04Cell\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1e.dopov.p.julian.admin.CellKindR\x04kind\x12H\n" +
	"\fcontent_type\x18\x03 \x01(\x0e2%.dopov.p.julian.admin.CellContentTypeR\vcontentType\x12+\n" +
	"\x12can_has_few_orders\x18\x04 \x01(\bR\x0fcanHasFewOrders\"\x8d\x01\n" +
	"\x11CreateCellRequest\x12@\n" +
	"\x04data\x18\x01 \x01(\v2,.dopov.p.julian.admin.CreateCellRequest.DataR\x04data\x1a6\n" +
	"\x04Data\x12.\n" +
	"\x04cell\x18\x01 \x01(\v2\x1a.dopov.p.julian.admin.CellR\x04cell\"\x14\n" +
	"\x12CreateCellResponse\"{\n" +
	"\x16MarkCellDeletedRequest\x12E\n" +
	"\x04data\x18\x01 \x01(\v21.dopov.p.julian.admin.MarkCellDeletedRequest.DataR\x04data\x1a\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x17MarkCellDeletedResponse*\x8d\x01\n" +
	"\bCellKind\x12\x19\n" +
	"\x15CELL_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCELL_KIND_WAREHOUSE_STORAGE\x10\x01\x12(\n" +
	"$CELL_KIND_WAREHOUSE_HANDLE_CONTAINER\x10\x02\x12\x1b\n" +
	"\x17CELL_KIND_WAREHOUSE_BOX\x10\x03*\xf7\x01\n" +
	"\x0fCellContentType\x12!\n" +
	"\x1dCELL_CONTENT_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$CELL_CONTENT_TYPE_EXPENDABLE_PRODUCT\x10\x01\x12\"\n" +
	"\x1eCELL_CONTENT_TYPE_MAIN_PRODUCT\x10\x02\x12'\n" +
	"#CELL_CONTENT_TYPE_OVERSIZED_PRODUCT\x10\x03\x12'\n" +
	"#CELL_CONTENT_TYPE_EXPENDABLE_LIQUID\x10\x04\x12!\n" +
	"\x1dCELL_CONTENT_TYPE_MAIN_LIQUID\x10\x052\xdc\x01\n" +
	"\x05Admin\x12a\n" +
	"\n" +
	"CreateCell\x12'.dopov.p.julian.admin.CreateCellRequest\x1a(.dopov.p.julian.admin.CreateCellResponse\"\x00\x12p\n" +
	"\x0fMarkCellDeleted\x12,.dopov.p.julian.admin.MarkCellDeletedRequest\x1a-.dopov.p.julian.admin.MarkCellDeletedResponse\"\x00B3Z1github.com/dopov-p/julian/internal/pb/admin;adminb\x06proto3"

var (
	file_api_admin_proto_rawDescOnce sync.Once
	file_api_admin_proto_rawDescData []byte
)

func file_api_admin_proto_rawDescGZIP() []byte {
	file_api_admin_proto_rawDescOnce.Do(func() {
		file_api_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_admin_proto_rawDesc), len(file_api_admin_proto_rawDesc)))
	})
	return file_api_admin_proto_rawDescData
}

var file_api_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_admin_proto_goTypes = []any{
	(CellKind)(0),                       // 0: dopov.p.julian.admin.CellKind
	(CellContentType)(0),                // 1: dopov.p.julian.admin.CellContentType
	(*Cell)(nil),                        // 2: dopov.p.julian.admin.Cell
	(*CreateCellRequest)(nil),           // 3: dopov.p.julian.admin.CreateCellRequest
	(*CreateCellResponse)(nil),          // 4: dopov.p.julian.admin.CreateCellResponse
	(*MarkCellDeletedRequest)(nil),      // 5: dopov.p.julian.admin.MarkCellDeletedRequest
	(*MarkCellDeletedResponse)(nil),     // 6: dopov.p.julian.admin.MarkCellDeletedResponse
	(*CreateCellRequest_Data)(nil),      // 7: dopov.p.julian.admin.CreateCellRequest.Data
	(*MarkCellDeletedRequest_Data)(nil), // 8: dopov.p.julian.admin.MarkCellDeletedRequest.Data
}
var file_api_admin_proto_depIdxs = []int32{
	0, // 0: dopov.p.julian.admin.Cell.kind:type_name -> dopov.p.julian.admin.CellKind
	1, // 1: dopov.p.julian.admin.Cell.content_type:type_name -> dopov.p.julian.admin.CellContentType
	7, // 2: dopov.p.julian.admin.CreateCellRequest.data:type_name -> dopov.p.julian.admin.CreateCellRequest.Data
	8, // 3: dopov.p.julian.admin.MarkCellDeletedRequest.data:type_name -> dopov.p.julian.admin.MarkCellDeletedRequest.Data
	2, // 4: dopov.p.julian.admin.CreateCellRequest.Data.cell:type_name -> dopov.p.julian.admin.Cell
	3, // 5: dopov.p.julian.admin.Admin.CreateCell:input_type -> dopov.p.julian.admin.CreateCellRequest
	5, // 6: dopov.p.julian.admin.Admin.MarkCellDeleted:input_type -> dopov.p.julian.admin.MarkCellDeletedRequest
	4, // 7: dopov.p.julian.admin.Admin.CreateCell:output_type -> dopov.p.julian.admin.CreateCellResponse
	6, // 8: dopov.p.julian.admin.Admin.MarkCellDeleted:output_type -> dopov.p.julian.admin.MarkCellDeletedResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_admin_proto_init() }
func file_api_admin_proto_init() {
	if File_api_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_admin_proto_rawDesc), len(file_api_admin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_admin_proto_goTypes,
		DependencyIndexes: file_api_admin_proto_depIdxs,
		EnumInfos:         file_api_admin_proto_enumTypes,
		MessageInfos:      file_api_admin_proto_msgTypes,
	}.Build()
	File_api_admin_proto = out.File
	file_api_admin_proto_goTypes = nil
	file_api_admin_proto_depIdxs = nil
}
